# GitHub Sponsors (not used for now)
github: []

# Patreon / Ko-fi / BuyMeACoffee (tak aktif sekarang)
patreon: ""
ko_fi: ""
buy_me_a_coffee: ""

# Open Collective (kosong buat masa ni)
open_collective: ""

# Custom donation/sponsor links
custom:
  - "https://autodigitalcoin.com"
  - "https://t.me/ADCoinhelpline"
  - "https://adcoin-validator-ai.onrender.com"
